version: '3'
networks:
  man-net:
    driver: bridge
services:
  indexer:
    image: registry.cn-hangzhou.aliyuncs.com/metaid/man-indexer:0.1
    networks:
      - man-net
    container_name: man-indexer
    stdin_open: true
    tty: true
    privileged: true
    build: 
      context: .
      args:
        VER: ${VER}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongodb
    command: >
      sh -c "/man/get-app.sh ${URL} &&
      /man/releases/linux/manindexer -test=${TEST} -chain=${CHAIN} -btc_height=${BTC_STARTING_BLOCK_HEIGHT}  -btc_rpc_host=${BTC_RPC_HOST}  -btc_rpc_user=${BTC_RPC_USER}  -btc_rpc_password=${BTC_RPC_PASSWORD}  -btc_zmqpubrawtx=${BTC_ZMQPUBRAWTX}  -mvc_height=${MVC_STARTING_BLOCK_HEIGHT} -mvc_rpc_host=${MVC_RPC_HOST}  -mvc_height=${MVC_STARTING_BLOCK_HEIGHT}  -mvc_rpc_user=${MVC_RPC_USER} -mvc_rpc_password=${MVC_RPC_PASSWORD}  -mvc_zmqpubrawtx=${MVC_ZMQPUBRAWTX} -server_port=:${SERVER_PORT}  -https_pem_file=${HTTPS_PEM_FILE}  -https_key_file=${HTTPS_KEY_FILE}  -domain_name=${DOMAIN_NAME}   -mongo_uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@man-mongodb:27017  -mongo_db_name=${MONGO_DB_NAME}"
  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/metaid/man-mongodb:7.0
    #image: mongo:latest
    container_name: man-mongodb
    restart: always
    networks:
      - man-net
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${DATA_DIR}/data:/data/db
    command:
      - "--auth"